version: "3.9"

services:
    web:
        image: nginx:latest
        volumes:
            - ./../api:/var/www/html
            - ./default.conf:/etc/nginx/conf.d/default.conf
        links:
            - php-fpm
        ports:
            - "8080:80"
    php-fpm:
        build: ./php
        volumes:
            - ./../api:/var/www/html
            - ./php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
            - ./php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
            - ./../cdn/public:/cdn
            - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf
        depends_on:
            - database
        extra_hosts:
            - "host.docker.internal:host-gateway"

    cdn:
        image: node:latest
        volumes:
            - ./../cdn:/src
            - ./../api/config/jwt:/src/jwt
        working_dir: /src
        ports:
            - "3000:3000"
        command: node app.js
    database:
        image: 'mariadb:10.3'
        container_name: database
        restart: always
        environment:
            - MYSQL_USER=op
            - MYSQL_PASSWORD=b1otope
            - MYSQL_DATABASE=op
            - MYSQL_ROOT_PASSWORD=b1otope

        ports:
            - '3306:3306'
        volumes:
            - ${PWD}/mariadb/:/var/lib/mysql/


