name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'master'
          submodules: 'true'
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Install npm dependencies
        run: cd app && npm install
      - name: Run build task
        run: cd app && npm run build --if-present
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "app/dist/"
          REMOTE_HOST: 'queel.io'
          REMOTE_USER: 'ubuntu'
          TARGET: "front/app"
          EXCLUDE: "/dist/, /node_modules/"
