name: Deploy back
on: [ push, pull_request ]
jobs:
  code-quality:
    name: PHPStan & PHP-CS-Fixer
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ '8.1' ]
      fail-fast: false
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - uses: actions/checkout@v3
        with:
          ref: 'main'
      - name: Retrieve pem and copy it to file
        env:
          PRIVATE_PEM: ${{ secrets.PRIVATE_PEM }}
          PUBLIC_PEM: ${{ secrets.PUBLIC_PEM }}
          ENV: ${{ secrets.ENV }}
        run: |
          mkdir -p api/config/jwt
          echo $PRIVATE_PEM | base64 -di > api/config/jwt/private.pem
          echo $PUBLIC_PEM | base64 -di > api/config/jwt/public.pem
          echo $ENV | base64 -di > api/.env


      - name: Composer Install
        run: cd api && composer install --ansi --prefer-dist --no-interaction --no-progress

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rltgoDzvO --no-g --delete"
          SOURCE: "api"
          REMOTE_HOST: 'queel.io'
          REMOTE_USER: 'ubuntu'
          TARGET: "/home/ubuntu/"
      - name: Executing migration scrip
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: 'queel.io'
          username: 'ubuntu'
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            docker exec -i php /bin/bash -c "bin/console doctrine:schema:update --force"
            sudo chown -R ubuntu:ubuntu api